### ISSUE TITLE
邀请您参加 “计图开发者交流会-优秀开源项目评选”

### ISSUE THREAD

**Issue by lzhengning** [CRNN-Jittor/CRNN-Jittor#1]
您好，感谢您使用计图 Jittor，并公布了此开源项目。我们诚挚邀请您参加优秀开源项目评选，于 12月25日 在首届计图开发者交流会 JDC2021 上颁奖  https://cg.cs.tsinghua.edu.cn/jittor/news/2021-12-19-00-00-jdc/。

请问您能否提供联系方式；或者将此项目链接发邮件至 "lzhengning (at) gmail.com"，我将回复您详细的参评方式。

**Comment by t4rf9** [comment]
already got in contact
